
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 18 12:17:43 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int PLUS = 21;
  public static final int LP = 3;
  public static final int _real = 16;
  public static final int SEMI = 7;
  public static final int RP = 4;
  public static final int _int = 14;
  public static final int in = 18;
  public static final int ID = 9;
  public static final int LCB = 5;
  public static final int LB = 11;
  public static final int _char = 15;
  public static final int RB = 13;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int EPSILON = 10;
  public static final int MAIN = 2;
  public static final int DIV = 24;
  public static final int CONST = 12;
  public static final int error = 1;
  public static final int read = 19;
  public static final int ASSIGN = 25;
  public static final int RCB = 6;
  public static final int MIN = 22;
  public static final int write = 20;
  public static final int MUL = 23;
  public static final int _for = 17;
}

